#!/usr/bin/python
#this module used to transfer files written by ponychen

import subprocess


def elk2pos():
    #this function transfer elk.in to POSCAR
    f = open("orig/elk.in","r+")
    inputfile = f.readlines()
    f.close()
    tmp = int(subprocess.getoutput(" grep -in ^avec orig/elk.in| awk 'BEGIN{FS=\":\"}{print $1}' "))
    axis = []
    for i in range(tmp,tmp+3):
        axis.append(list(map(float,inputfile[i].split())))
    spenum = int(subprocess.getoutput(" grep -in ^atoms orig/elk.in|awk 'BEGIN{FS=\":\"}{print $1}' "))
    tmp = 0
    spe1 = []
    spe2 = []
    cord = []
    spenum += 1
    for i in range(int(inputfile[spenum-1].split()[0])):
        spe1.append(inputfile[spenum+tmp].split()[0])
        spe2.append(int(inputfile[spenum+tmp+1].split()[0]))
        for j in range(spenum+tmp+2,spenum+tmp+2+spe2[i]):
            cord.append(list(map(float,inputfile[j].split()[:3])))
        tmp += 2+spe2[i]
    for i in range(int(inputfile[spenum-1].split()[0])):
        spe1[i] = spe1[i][1:-4]
    for i in axis:
        for j in range(3):
            i[j] *= 0.5292
    ifscale = subprocess.getoutput(" grep -in ^scale orig/elk.in|awk 'BEGIN{FS=\":\"}{print $1}'")
    if ifscale:
        scale = float(inputfile[int(ifscale)+1])
    else:
        scale = 1.0
    
    f = open("orig/POSCAR","w+")
    f.write("generated by ponychen\n")
    f.write(str(scale)+"\n")
    for i in range(3):
        f.write("%9.6f %9.6f %9.6f\n" % (axis[i][0],axis[i][1],axis[i][2]))
    f.write(" ".join(spe1)+"\n")
    f.write(" ".join(list(map(str,spe2)))+"\n")
    f.write("Direct\n")
    for i in cord:
        f.write(" ".join(list(map(str,i)))+"\n")
    f.close()

